# Generated by Django 4.1.7 on 2023-03-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeMenu.treemenu'),
        ),
    ]
